# Generated by Django 4.1 on 2022-09-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
        migrations.CreateModel(
            name='partner_categories',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'partner_categories',
            },
        ),
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('category_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='partners')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'partners',
            },
        ),
    ]
