# Generated by Django 4.1 on 2022-09-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='image',
            field=models.ImageField(blank=True, upload_to='clients'),
        ),
    ]
